on: push
name: Main Workflow
jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: make test
      - run: cat bin/cov.out 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: bin/cov.out

  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download code coverage results
      uses: actions/download-artifact@v1
      with:
        name: code-coverage-report
        path: bin/cov.out
    - run: ls -lah bin/cov.out
    - run: ls -lah /home/runner/work/service_sonar/service_sonar/bin/cov.out 
    - run: cat /home/runner/work/service_sonar/service_sonar/bin/cov.out 
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}